name: Action

on:
  push:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python environment using conda
        uses: conda-incubator/setup-miniconda@v3.2.0
        with:
          auto-update-conda: false
          activate-environment: action
          environment-file: environment.yml
          use-only-tar-bz2: true
          channel-priority: strict

      - run: |
          conda info
          python --version